name: Fourmolu
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      # Note that you must checkout your code before running fourmolu/fourmolu-action
      - uses: actions/checkout@v3
      - uses: fourmolu/fourmolu-action@v4
